# Generated by Django 4.1.3 on 2023-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('product_size', models.CharField(choices=[('20x20', '20 x 20'), ('30x30', '30 x 30')], max_length=10)),
                ('category', models.CharField(choices=[('porcelain', 'Porcelain Tiles'), ('ceramic', 'Ceramic Tiles'), ('adhesive', 'Adhesive'), ('sanitary wares', 'Sanitary Wares')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_stock', models.PositiveIntegerField()),
                ('date_last_stocked', models.DateTimeField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
