# Generated by Django 4.1.3 on 2023-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('20x20', '20 x 20'), ('30x30', '30 x 30')], max_length=10, null=True),
        ),
    ]
