# Generated by Django 4.1.3 on 2023-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_alter_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_stocked',
            field=models.DateTimeField(null=True),
        ),
    ]
