# Generated by Django 4.1.3 on 2023-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_alter_product_date_last_stocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_stocked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
