# Generated by Django 4.1.3 on 2023-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0004_alter_product_date_last_stocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Porcelain Tiles', 'Porcelain Tiles'), ('Ceramic Tiles', 'Ceramic Tiles'), ('Adhesive', 'Adhesive'), ('Sanitary Wares', 'Sanitary Wares')], max_length=20),
        ),
    ]
