# Generated by Django 4.1.3 on 2023-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('20 x 20', '20 x 20'), ('30 x 30', '30 x 30'), ('60 x 30', '60 x 30')], max_length=10, null=True),
        ),
    ]
