# Generated by Django 4.1.3 on 2023-02-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0006_alter_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='blog-images/'),
        ),
    ]
