# Generated by Django 4.1.3 on 2023-02-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0008_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
