# Generated by Django 4.1.3 on 2023-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0009_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_last_stocked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='Dunmark.png', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
