# Generated by Django 4.2 on 2023-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0010_alter_product_brand_alter_product_date_last_stocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('size', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stocks', models.IntegerField()),
                ('date_archived', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
