# Generated by Django 4.2 on 2023-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0011_productarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='productarchive',
            name='product_img',
            field=models.ImageField(default='Dunmark.png', upload_to='product_archives'),
        ),
    ]
