# Generated by Django 4.2 on 2023-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productarchive',
            name='brand',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
