# Generated by Django 4.1.3 on 2023-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0016_productcategory_tilesizes_alter_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='size',
            new_name='category',
        ),
    ]
