# Generated by Django 4.1.3 on 2023-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0019_alter_product_category_alter_product_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tilesize',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tilesize',
            name='size',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
