# Generated by Django 4.1.3 on 2023-05-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_occur',
            field=models.DateField(auto_now=True),
        ),
    ]
