# Generated by Django 4.1.3 on 2023-05-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_notification_date_occur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='item_name',
        ),
    ]
