# Generated by Django 4.1.3 on 2023-05-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_remove_notification_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
