# Generated by Django 4.1.3 on 2023-05-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
