# Generated by Django 4.1.3 on 2023-04-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuthentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
