# Generated by Django 4.1.3 on 2023-04-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAuthentication', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
