# Generated by Django 4.1.3 on 2023-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=40)),
                ('phone_number', models.CharField(max_length=11)),
                ('permanent_address', models.CharField(max_length=60)),
                ('delivery_address', models.CharField(max_length=60)),
                ('credit_eligibility', models.BooleanField(default=True)),
            ],
        ),
    ]
