# Generated by Django 4.2 on 2023-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0004_alter_customer_credit_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_eligibility',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible')], max_length=20),
        ),
    ]
