# Generated by Django 4.1.3 on 2023-05-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitorsPage', '0002_contact_email_contact_location_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
