# Generated by Django 4.2 on 2023-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturnProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productarchive',
            name='date_archived',
            field=models.DateField(auto_now=True),
        ),
    ]
