# Generated by Django 4.2 on 2023-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturnProduct', '0002_productarchive_date_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productarchive',
            name='date_archived',
            field=models.DateField(auto_now_add=True),
        ),
    ]
