# Generated by Django 4.1.3 on 2023-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturnProduct', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='orig_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
