# Generated by Django 4.1.3 on 2023-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturnProduct', '0006_returnitem_orig_quantity_returnitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='status',
        ),
        migrations.AddField(
            model_name='returnitem',
            name='date_returned',
            field=models.DateField(auto_now=True),
        ),
    ]
