# Generated by Django 4.1.3 on 2023-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReturnProduct', '0007_remove_returnitem_status_returnitem_date_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='description',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
