# Generated by Django 4.1.3 on 2023-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
