# Generated by Django 4.1.3 on 2023-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0002_alter_transaction_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_address',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
