# Generated by Django 4.1.3 on 2023-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0003_alter_transaction_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_address',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
