# Generated by Django 4.1.3 on 2023-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0004_alter_transaction_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='transaction_no',
            field=models.IntegerField(),
        ),
    ]
