# Generated by Django 4.1.3 on 2023-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0005_alter_item_product_id_alter_item_transaction_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=5, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default=4, max_length=15),
            preserve_default=False,
        ),
    ]
