# Generated by Django 4.1.3 on 2023-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0006_item_name_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('pending', 'Pending')], max_length=10, null=True),
        ),
    ]
