# Generated by Django 4.1.3 on 2023-03-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0008_transaction_gcash_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Gcash_no',
            new_name='gcash_no',
        ),
    ]
