# Generated by Django 4.1.3 on 2023-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0010_alter_transaction_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='banking_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit'), ('cheque', 'Cheque')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
