# Generated by Django 4.1.3 on 2023-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0011_transaction_account_name_transaction_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='banking_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Cheque', 'Cheque')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
