# Generated by Django 4.2 on 2023-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0012_alter_transaction_banking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
