# Generated by Django 4.2 on 2023-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0014_alter_transaction_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment',
            field=models.CharField(blank=True, default='false', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Gcash', 'Gcash'), ('Banking', 'Banking')], max_length=20),
        ),
    ]
