# Generated by Django 4.2 on 2023-04-10 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0021_alter_transaction_installment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(choices=[('false', '----- Select Payment Method -----'), ('Cash', 'Cash'), ('Gcash', 'Gcash'), ('Banking', 'Banking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='transaction_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 29, 6, 638020)),
        ),
    ]
