# Generated by Django 4.2 on 2023-04-10 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0023_alter_transaction_installment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(choices=[('false', '----- Select Payment Method -----'), ('Cash', 'Cash'), ('Gcash', 'Gcash'), ('Banking', 'Banking')], default='false', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 30, 14, 789151)),
        ),
    ]
