# Generated by Django 4.2 on 2023-04-10 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0025_alter_installment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 14, 44, 31, 411137)),
        ),
    ]
