# Generated by Django 4.2 on 2023-04-11 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0026_alter_installment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='installment_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 0, 40, 33, 786760)),
        ),
    ]
