# Generated by Django 4.1.3 on 2023-04-30 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesTransaction', '0050_alter_transaction_banking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='installment_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 53, 25, 459925)),
        ),
    ]
